# -*- encoding:utf-8 -*-
"""
Django settings for auto_ui project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this conf, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# import pymysql
# import django.middleware.security.SecurityMiddleware,django.contrib.sessions.middleware.SessionMiddleware
# import django.middleware.common.CommonMiddleware,django.middleware.csrf.CsrfViewMiddleware
# import django.contrib.auth.middleware.AuthenticationMiddleware
# import django.contrib.messages.middleware.MessageMiddleware,  django.middleware.clickjacking.XFrameOptionsMiddleware
# import django_redis.cache.RedisCache
import django.db.backends.mysql

from auto_ui.Config import get_yaml_local

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# pymysql.install_as_MySQLdb()
y = get_yaml_local(BASE_DIR)
# djcelery.setup_loader()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*f4!k51p@y-+1qga=fgt=wd$&@zhcw!6%=@%x3nqu5ql19!o(%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    # 'rest_framework',
    'taskmanage',
    'jcanayls',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mymiddleware.addUserNameMiddleWare',
]

ROOT_URLCONF = 'auto_ui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto_ui.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': y["db"]["oname"],
        'USER': y["db"]["uname"],
        'PASSWORD': y["db"]["passwd"],
        'HOST': y["db"]["ip"],
        'PORT': y["db"]["port"],
        # 'OPTIONS': {'isolation_level': None}
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://192.168.70.151:6379",
#         "TIMEOUT": 60 * 60,
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "CONNECTION_POOL_KWARGS": {"max_connections": 100},
#             "PASSWORD": "12345"
#         }
#     }
# }

# CELERY STUFF
# BROKER_URL = 'redis://192.168.70.151:6379'
# CELERY_RESULT_BACKEND = 'redis://192.168.70.151:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Shanghai'

# MONGODB = {'ip': '', 'port': 27017, 'NAME': 'test', 'collections': 'taskdata'}
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_CACHE_ALIAS = "default"

REDIS_TIMEOUT = 60 * 60
WORKING_REDIS_TIMEOUT = 60 * 60 * 3
REDIS_TIMEOUT_DAY = 24 * 60 * 60
NEVER_REDIS_TIMEOUT = 365 * 24 * 60 * 60

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')
MEDIA_URL = '/images/'
LOGIN_URL = '/home/login/'
